// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug: Check Supabase credentials
console.log('🔧 [Supabase Client] Initializing...');
console.log('🔧 [Supabase URL]:', SUPABASE_URL || '❌ MISSING');
console.log('🔧 [Supabase Key]:', SUPABASE_PUBLISHABLE_KEY ? '✅ Present' : '❌ MISSING');

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ [Supabase Client] Missing credentials! Check .env file');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

console.log('✅ [Supabase Client] Initialized successfully');