// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("❌ Supabase environment variables are missing!");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: "pkce",
    },
    global: {
      headers: {
        "x-client-info": "ncrm-web",
      },
    },
  },
);

// ==========================================
// 🔧 Fix: Override functions.invoke to avoid CORS issue
// The Supabase JS client sends x-supabase-client-platform header
// which the deployed Edge Functions don't allow yet.
// This wrapper uses fetch directly with clean headers.
// ==========================================
const originalInvoke = supabase.functions.invoke.bind(supabase.functions);
supabase.functions.invoke = async (functionName: string, options?: any) => {
  const {
    data: { session },
  } = await supabase.auth.getSession();
  const token = session?.access_token;

  const url = `${SUPABASE_URL}/functions/v1/${functionName}`;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    apikey: SUPABASE_PUBLISHABLE_KEY,
    "x-client-info": "ncrm-web",
  };
  if (token) {
    headers["Authorization"] = `Bearer ${token}`;
  }

  try {
    const resp = await fetch(url, {
      method: options?.method || "POST",
      headers,
      body: options?.body
        ? typeof options.body === "string"
          ? options.body
          : JSON.stringify(options.body)
        : undefined,
    });

    const contentType = resp.headers.get("content-type") || "";
    let data: any;
    if (contentType.includes("application/json")) {
      data = await resp.json();
    } else {
      data = await resp.text();
    }

    if (!resp.ok) {
      return {
        data: null,
        error: {
          message: data?.error || data || `HTTP ${resp.status}`,
          context: { statusCode: resp.status },
        },
      };
    }

    return { data, error: null };
  } catch (e: any) {
    return { data: null, error: { message: e.message } };
  }
};
